### ISSUE TITLE
？

### ISSUE THREAD

**Issue by jiyuanzhao0311** [gunnerwang/Self-Adaptive-Modeling-Manufacturing-Process#1]
请问你这个数据集是什么，为什么都是乱码

**Comment by gunnerwang** [comment]
请用with open打开，都是处理过的时间序列数据。

**Comment by jiyuanzhao0311** [comment]
谢谢您的回复！！



---- Replied Message ----
| From | ***@***.***> |
| Date | 11/27/2024 12:10 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [gunnerwang/Self-Adaptive-Modeling-Manufacturing-Process] ？ (Issue #1) |

Closed #1 as completed.
